### ISSUE TITLE
[ZEON] - recommended additions

### ISSUE THREAD

**Issue by zeon-neon** [NeonGamerBot-QK/spotify-parse-csv#1]
# Meta

- [ ] Github repo has no description [enable here](https://github.com/NeonGamerBot-QK/spotify-parse-csv)

- [ ] There is no homepage! [enable here](https://github.com/NeonGamerBot-QK/spotify-parse-csv)

- [ ] Your repo does not have web commit signing off enabled. **PLEASE ENABLE IT** [here](https://github.com/NeonGamerBot-QK/spotify-parse-csv/settings)

- [ ] This repo does not have discussions enabled

- [ ] This repo does not have a license

- [ ] This repo does not have a code of conduct (feature is in beta!)

- [ ] This repo does not have a license

- [ ] This repo does not have a code of conduct (feature is in beta!)

- [ ] undefined
# Automation

- [ ] **Mark this to override & close this issue.**
